# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Dependency-light UnifiedLLM data types.

These types are used by strategies, middleware, and tests. Keep this module
free of concrete provider imports so lightweight framework imports do not load
the full LiteLLM stack.
"""

import inspect
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, Literal

from pydantic import BaseModel


def _resolve_schema_refs(schema: dict[str, Any]) -> dict[str, Any]:
    """Resolve $ref references by inlining $defs definitions.

    Pydantic generates $ref/$defs for nested models. LLM APIs need
    flat schemas with type on every property. This inlines all
    references and removes $defs.
    """
    defs = schema.get("$defs", {})
    if not defs:
        return schema

    def _inline(node, _resolving=frozenset()):
        if not isinstance(node, dict):
            return node
        if "$ref" in node:
            ref_path = node["$ref"]
            if ref_path.startswith("#/$defs/"):
                def_name = ref_path[len("#/$defs/") :]
                if def_name in _resolving:
                    return {"type": "object"}  # break cycle for recursive models
                if def_name in defs:
                    return _inline(dict(defs[def_name]), _resolving | {def_name})
            # Unresolvable $ref (not in $defs or non-local) - replace with generic object
            # since LLM providers don't support $ref in tool schemas
            return {"type": "object"}
        result = {}
        for k, v in node.items():
            if k == "$defs":
                continue
            elif k == "properties" and isinstance(v, dict):
                result[k] = {pk: _inline(pv, _resolving) for pk, pv in v.items()}
            elif k in ("items", "additionalProperties") and isinstance(v, dict):
                result[k] = _inline(v, _resolving)
            elif k in ("anyOf", "oneOf", "allOf") and isinstance(v, list):
                result[k] = [_inline(i, _resolving) if isinstance(i, dict) else i for i in v]
            else:
                result[k] = v
        # Unwrap single-item allOf (Pydantic wraps $ref in allOf when Field has description)
        if "allOf" in result and len(result["allOf"]) == 1:
            merged = dict(result["allOf"][0])
            del result["allOf"]
            # Preserve sibling keys (e.g., description) alongside the unwrapped schema
            for k, v in result.items():
                if k not in merged:
                    merged[k] = v
            result = merged
        return result

    return _inline(schema)


def _strip_schema_noise(schema: dict[str, Any], *, strict: bool = False) -> dict[str, Any]:
    """Strip Pydantic noise (title, default) from a JSON schema recursively.

    These fields are auto-generated by Pydantic but add no value for LLM APIs
    and cause strict-mode rejections on some providers.

    When ``strict=True`` (OpenAI Responses API / Chat Completions strict mode):
    - Forces ``additionalProperties: false`` on every object type
    - Ensures every object has ``properties`` and ``required`` keys
    - Strips extra keys not in the strict-mode allowlist
    """
    STRIP_KEYS = frozenset({"title", "default"})
    # Strict mode only allows these keys (OpenAI spec)
    STRICT_ALLOWED = frozenset(
        {
            "type",
            "description",
            "enum",
            "const",
            "properties",
            "required",
            "items",
            "additionalProperties",
            "anyOf",
            "oneOf",
            "allOf",
        }
    )

    def _strip(node):
        if not isinstance(node, dict):
            return node
        if strict:
            cleaned = {k: v for k, v in node.items() if k in STRICT_ALLOWED}
        else:
            cleaned = {k: v for k, v in node.items() if k not in STRIP_KEYS}
        if "properties" in cleaned:
            cleaned["properties"] = {k: _strip(v) for k, v in cleaned["properties"].items()}
        if "items" in cleaned and isinstance(cleaned["items"], dict):
            cleaned["items"] = _strip(cleaned["items"])
        if "additionalProperties" in cleaned and isinstance(cleaned["additionalProperties"], dict):
            cleaned["additionalProperties"] = _strip(cleaned["additionalProperties"])
        for key in ("anyOf", "oneOf", "allOf"):
            if key in cleaned and isinstance(cleaned[key], list):
                cleaned[key] = [_strip(i) if isinstance(i, dict) else i for i in cleaned[key]]
        if strict and cleaned.get("type") == "object":
            cleaned["additionalProperties"] = False
            cleaned.setdefault("properties", {})
            cleaned["required"] = list(cleaned["properties"].keys())
        return cleaned

    return _strip(schema)


def _clean_schema(schema: dict[str, Any], *, strict: bool = False) -> dict[str, Any]:
    """Clean a Pydantic-generated JSON schema for LLM tool use.

    1. Resolves $ref/$defs inline (providers need flat schemas)
    2. Strips title/default noise (Pydantic artifacts, no LLM value)
    3. Ensures top-level structure has type/properties/required
    4. When ``strict=True``: enforces OpenAI strict-mode constraints
       (additionalProperties: false everywhere, properties+required on all objects)
    """
    resolved = _resolve_schema_refs(schema)
    cleaned = _strip_schema_noise(resolved, strict=strict)
    # Ensure standard top-level structure
    result = {
        "type": cleaned.get("type", "object"),
        "properties": cleaned.get("properties", {}),
        "required": cleaned.get("required", []),
    }
    if strict:
        result["additionalProperties"] = False
    return result


def _strict_schema_valid(schema: dict[str, Any]) -> bool:
    """Check whether a schema satisfies OpenAI strict-mode requirements.

    Every property node must have a ``type`` key (or ``anyOf``/``oneOf``),
    and every object must have ``required`` listing ALL property keys.
    Returns False if any node violates these constraints.
    """

    def _check(node: dict[str, Any]) -> bool:
        if not isinstance(node, dict):
            return True
        # A property node needs type or a union discriminator
        if (
            "type" not in node
            and "anyOf" not in node
            and "oneOf" not in node
            and "allOf" not in node
        ):
            return False
        # Object nodes: required must list every property key
        if (
            node.get("type") == "object"
            and "properties" in node
            and set(node.get("required", [])) != set(node["properties"].keys())
        ):
            return False
        # Array nodes: strict mode requires typed `items`. Strict cleaning drops
        # prefixItems (tuples) and other non-allowlisted array keywords, which can
        # leave an array with no usable `items` - the Responses API then rejects
        # "array schema missing items". Treat such arrays as strict-invalid so the
        # caller falls back to a Responses-safe non-strict schema. See issue 232.
        if node.get("type") == "array":
            items = node.get("items")
            if not isinstance(items, dict) or not any(
                k in items for k in ("type", "anyOf", "oneOf", "allOf", "enum", "const")
            ):
                return False
        for v in node.get("properties", {}).values():
            if isinstance(v, dict) and not _check(v):
                return False
        if isinstance(node.get("items"), dict) and not _check(node["items"]):
            return False
        for key in ("anyOf", "oneOf", "allOf"):
            for item in node.get(key, []):
                if isinstance(item, dict) and not _check(item):
                    return False
        return True

    return _check(schema)


@dataclass
class Tool:
    """Standardized tool representation across all LLM APIs.

    Clean design: Either provide parameters_model (Pydantic) or it's auto-generated from callable.

    - parameters_model: Pydantic model defining parameter schema (recommended)
    - If None, auto-generates from callable's signature
    - Preserves all type information (Union, nested models, TypedDict, etc.)
    """

    name: str
    description: str
    callable: Callable
    parameters_model: type[BaseModel] | None = None  # Pydantic model for parameters

    def get_parameter_schema(self, *, strict: bool = False) -> dict[str, Any]:
        """Get the JSON schema for parameters.

        If parameters_model is provided, use its schema.
        Otherwise, auto-generate from callable signature.

        The returned schema has $ref resolved inline and Pydantic noise
        (title, default) stripped - clean for any LLM provider.

        Args:
            strict: When True, enforce OpenAI strict-mode constraints
                (additionalProperties: false everywhere, all objects need
                properties+required).
        """
        if self.parameters_model is not None:
            schema = self.parameters_model.model_json_schema()
        else:
            schema = self._auto_generate_raw_schema()

        return _clean_schema(schema, strict=strict)

    def _auto_generate_raw_schema(self) -> dict[str, Any]:
        """Auto-generate parameter schema from callable signature."""
        from pydantic import create_model

        sig = inspect.signature(self.callable)
        field_definitions = {}

        for param_name, param in sig.parameters.items():
            if param_name == "self":
                continue

            param_type = param.annotation if param.annotation != inspect.Parameter.empty else str
            default = ... if param.default == inspect.Parameter.empty else param.default

            field_definitions[param_name] = (param_type, default)

        if not field_definitions:
            # No parameters
            return {"type": "object", "properties": {}, "required": []}

        # Create temporary Pydantic model
        TempModel = create_model(f"{self.name}_params", **field_definitions)
        return TempModel.model_json_schema()


def create_tool_from_callable(tool_callable: Callable) -> Tool:
    """Extract Tool metadata from a Python function.

    Creates a Tool with auto-generated parameter schema from the callable's signature.
    """
    docstring = tool_callable.__doc__ or f"Call the {tool_callable.__name__} function"

    # Let Tool auto-generate the schema from the callable
    return Tool(
        name=tool_callable.__name__,
        description=docstring,
        callable=tool_callable,
        parameters_model=None,  # Will auto-generate from signature
    )


@dataclass
class ToolCall:
    """Standardized tool call representation across all LLM APIs."""

    id: str
    name: str
    arguments: str


@dataclass
class LLMResponse:
    """Standardized response from any LLM API."""

    raw_response: Any
    content: str | BaseModel
    tool_calls: list[ToolCall]
    finish_reason: Literal["stop", "tool_calls", "length", "error"]
    assistant_message: dict[str, Any]
    reasoning: str | None = None  # o1-style or DeepSeek/QwQ reasoning
    usage: dict[str, int] | None = None  # Token usage stats

    @property
    def message(self) -> str | BaseModel | None:
        """Backward-compatible alias for content."""
        return self.content


__all__ = [
    "LLMResponse",
    "Tool",
    "ToolCall",
    "create_tool_from_callable",
]
